# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embed2.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embed2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65mbed2.proto\x12\x05\x65mbed\",\n\x0c\x45mbedRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\"\n\rEmbedResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\":\n\x11\x45mbedBatchRequest\x12%\n\x08requests\x18\x01 \x03(\x0b\x32\x13.embed.EmbedRequest\"=\n\x12\x45mbedBatchResponse\x12\'\n\tresponses\x18\x01 \x03(\x0b\x32\x14.embed.EmbedResponse2\x85\x01\n\x0c\x45mbedService\x12\x32\n\x05\x45mbed\x12\x13.embed.EmbedRequest\x1a\x14.embed.EmbedResponse\x12\x41\n\nEmbedBatch\x12\x18.embed.EmbedBatchRequest\x1a\x19.embed.EmbedBatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embed2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDREQUEST']._serialized_start=23
  _globals['_EMBEDREQUEST']._serialized_end=67
  _globals['_EMBEDRESPONSE']._serialized_start=69
  _globals['_EMBEDRESPONSE']._serialized_end=103
  _globals['_EMBEDBATCHREQUEST']._serialized_start=105
  _globals['_EMBEDBATCHREQUEST']._serialized_end=163
  _globals['_EMBEDBATCHRESPONSE']._serialized_start=165
  _globals['_EMBEDBATCHRESPONSE']._serialized_end=226
  _globals['_EMBEDSERVICE']._serialized_start=229
  _globals['_EMBEDSERVICE']._serialized_end=362
# @@protoc_insertion_point(module_scope)
